In [2]:
import seaborn as sns
import numpy as np
from math import exp
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

In [3]:
iris = datasets.load_iris()
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [4]:
X = iris["data"][:, 3:] # petal width
y = (iris["target"] == 2).astype(int)

In [13]:
alpha = 0.1
iterations = 1500
n = 100
beta = np.random.randn(2, 1)
X_b = np.c_[np.ones((len(X), 1)), X]
y_b = y[..., None]
gradient = None
for _ in range(iterations):
    gradient = 1/n * X_b.T.dot((1/(1 + np.exp(-X_b.dot(beta)))) - y_b)
    beta = beta - alpha * gradient
beta

array([[-6.95820712],
       [ 4.26915633]])

### Stochastic gradient descent for logistic regression

In [19]:
alpha = 0.1
iterations = 7000
beta = np.random.randn(2, 1)
X_b = np.c_[np.ones((len(X), 1)), X]
y_b = y[..., None]
gradient = None

epochs = 100
t0, t1 = 5, 50

def learning_schedule(t):
    return t0/(t + t1)

for epoch in range(epochs):
    for _ in range(iterations):
        index = np.random.randint(len(X_b))
        xi = X_b[index: index+1]
        yi = y_b[index: index+1]
        gradient = 1/len(X) * xi.T.dot((1/(1 + np.exp(-xi.dot(beta)))) - yi)
        beta = beta - learning_schedule(epoch) * gradient
beta

array([[-7.5061911 ],
       [ 4.60085129]])

In [8]:
log_reg = LogisticRegression()
log_reg.fit(X, y)
log_reg.intercept_, log_reg.coef_

(array([-7.1947083]), array([[4.3330846]]))